name: coding_challenge
description: A new coding challenge.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^3.1.1
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_facebook_auth: ^3.5.2
  font_awesome_flutter: ^9.1.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.1
  graphql_flutter: ^5.0.0
  hive: ^2.0.4
  injectable: ^1.5.0
  internet_connection_checker: ^0.0.1+2

dev_dependencies:
  build_runner: ^2.1.2
  dartz: ^0.10.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true
