name: coding_challenge
description: A new coding challenge.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.1.1
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^3.5.2
  font_awesome_flutter: ^9.1.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.11
  google_sign_in: ^5.1.1
  graphql_flutter: ^5.0.0
  hive: ^2.0.4
  injectable: ^1.5.0
  internet_connection_checker: ^0.0.1+2
  json_annotation: ^4.1.0
  location: ^4.3.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.12

dev_dependencies:
  build_runner: ^2.1.2
  dartz: ^0.10.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.2
  json_serializable: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
