name: coding_challenge
description: A new coding challenge.

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^7.1.1
  font_awesome_flutter: ^10.8.0
  function_tree: ^0.9.1
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  google_sign_in: ^6.2.2
  graphql_flutter: ^5.0.0
  hive: ^2.0.4
  injectable: ^2.5.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.1.0
  location: ^7.0.1
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.12

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - .env
