// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcWH_kCg14NFN6hbMldRixUgupCLsXgwU',
    appId: '1:36700177055:android:71a834544aac9ee34418aa',
    messagingSenderId: '36700177055',
    projectId: 'coding-challenge-ef64a',
    storageBucket: 'coding-challenge-ef64a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE_xGRqke1FGuqGr9KRvU6vp8mvz7E0e4',
    appId: '1:36700177055:ios:00b4480c0286c6e74418aa',
    messagingSenderId: '36700177055',
    projectId: 'coding-challenge-ef64a',
    storageBucket: 'coding-challenge-ef64a.firebasestorage.app',
    androidClientId: '36700177055-cu4pmkfnr9h7l6u4lvfnimnj88fau4kc.apps.googleusercontent.com',
    iosClientId: '36700177055-qpqjhprm39m0kh2agfmjcgoap685g7t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingChallenge',
  );
}
